name: Build the sample

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build Debug APK
      run: ./gradlew sample:assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: ./sample/build/outputs/apk/debug/sample-debug.apk
